### ISSUE TITLE
Support for AFNetworking 4.0.0. Older versions invalid due to UIWebView 

### ISSUE THREAD

**Issue by Seoras** [kubatruhlar/AFNetworking-RetryPolicy#10]
Pods won't update AFNetworking to 4.0.0 due to AFNetworking-RetryPolicy placing a version limit on it. I understand there are some API changes which will require work. Happy to help?

**Comment by rajlakshmi12** [comment]
Is there any update on it? Do we have AFNetworking-RetryPolicy pod with updated AFNetworking dependency to 4.0.0, Please help.

**Comment by kubatruhlar** [comment]
Sure, feel free to contribute.

**Comment by kubatruhlar** [comment]
Made the category compatible with _AFNetworking 4_. **Check the [v2.0.0](https://github.com/kubatruhlar/AFNetworking-RetryPolicy/tree/2.0.0).**
