### ISSUE TITLE
can't use branch afn2-support on podfile

### ISSUE THREAD

**Issue by fabionapodano** [kubatruhlar/AFNetworking-RetryPolicy#4]
I am trying to use this branch for AFNetworking2.x support, using the following line in my podfile:

> pod "AFNetworking+RetryPolicy", git: 'https://github.com/kubatruhlar/AFNetworking-RetryPolicy.git' , branch: 'afn2-support'

i get the following error:

> Unable to find a specification for 'AFNetworking+RetryPolicy'

the configuration seems to be ok, since the log says:

> Pre-downloading: `AFNetworking+RetryPolicy` from `https://github.com/kubatruhlar/AFNetworking-RetryPolicy.git`, branch `afn2-support`

**Comment by kubatruhlar** [comment]
I do not think that these branches are available through Cocoapods.

**Comment by kubatruhlar** [comment]
I updated every old branch so it is possible now. Check the `README.md` for more info. Thank you.
